#Templates
include:
  - project: 'sd-mana-tmo-prepaid-cdp-pristine/ppm-apps-templates/templates'
    ref: master
    file: 'jobs/wsil/ssl_cert/.job.publish.ssl-cert.yml'

  - project: 'sd-mana-tmo-prepaid-cdp-pristine/ppm-apps-templates/templates'
    ref: master
    file: 'jobs/wsil/ssl_cert/.job.deploy.ssl-cert.yml'

stages:
  - publish
  - deploy
  
publish:
  extends:
    - .publish_sslcert_template
  variables:
    TAR_NAME: "SSL_CERT.tgz"
    TAR_PATH: 'SSL_CERT'
  only:
    - master
  tags:
    - ecn-edpctl

deploy_cdpsdp1:
  extends:
    - .deploy_sslcert_template
  variables:
    SSH_USER: $SSH_USER
    SSH_PWD: $SSH_PWD
    DOWNLOAD_LOCATION: "$ARTIFACTORY_URL/$REPO_KEY_POC/ambassador/${CI_PIPELINE_ID}"
    REMOTE_LOCATION: '/deploy/bscs/Cert'
    CERT_NAME: 'pl-dev-cdp-sd1-bscs-traf.lab.uprising.t-mobile.com.p12'
    CERT_PWD: $CERT_PWD
    ENV_HOST: $CDPSD1_IP_ADDRESS
    FOLDER_TO_UPLOAD: 'SSL_CERT/CDPSD1'

deploy_DEV3:
  extends:
    - .deploy_sslcert_template
  variables:
    SSH_USER: $SSH_USER
    SSH_PWD: $SSH_PWD
    DOWNLOAD_LOCATION: "$ARTIFACTORY_URL/$REPO_KEY_POC/ambassador/${CI_PIPELINE_ID}"
    REMOTE_LOCATION: '/deploy/bscs/Cert'
    CERT_NAME: 'pl-l1-bscs-var-03-traf.pl.lab.uprising.t-mobile.com.p12'
    CERT_PWD: $CERT_PWD
    ENV_HOST: $DEV3_IP_ADDRESS
    FOLDER_TO_UPLOAD: 'SSL_CERT/DEV3'

deploy_DEV8:
  extends:
    - .deploy_sslcert_template
  variables:
    SSH_USER: $SSH_USER
    SSH_PWD: $SSH_PWD
    DOWNLOAD_LOCATION: "$ARTIFACTORY_URL/$REPO_KEY_POC/ambassador/${CI_PIPELINE_ID}"
    REMOTE_LOCATION: '/deploy/bscs/Cert'
    CERT_NAME: 'pl-l1-bscs-var-08-traf.pl.lab.uprising.t-mobile.com.p12'
    CERT_PWD: $CERT_PWD
    ENV_HOST: $DEV8_IP_ADDRESS
    FOLDER_TO_UPLOAD: 'SSL_CERT/DEV8'

deploy_QAT3:
  extends:
    - .deploy_sslcert_template
  variables:
    SSH_USER: $SSH_USER
    SSH_PWD: $SSH_PWD
    DOWNLOAD_LOCATION: "$ARTIFACTORY_URL/$REPO_KEY_POC/ambassador/${CI_PIPELINE_ID}"
    REMOTE_LOCATION: '/deploy/bscs/Cert'
    CERT_NAME: 'p0014-traf.pl.lab.uprising.t-mobile.com.p12'
    CERT_PWD: $CERT_PWD
    ENV_HOST: $QAT3_IP_ADDRESS
    FOLDER_TO_UPLOAD: 'SSL_CERT/QAT3'

deploy_DEV2:
  extends:
    - .deploy_sslcert_template
  variables:
    SSH_USER: $SSH_USER
    SSH_PWD:  $SSH_PWD
    DOWNLOAD_LOCATION: "$ARTIFACTORY_URL/$REPO_KEY_POC/ambassador/${CI_PIPELINE_ID}"
    REMOTE_LOCATION: '/deploy/bscs/Cert'
    CERT_NAME: 'pl-l1-bscs-var-02-traf.pl.lab.uprising.t-mobile.com.p12'
    CERT_PWD: $CERT_PWD
    ENV_HOST: $DEV2_IP_ADDRESS
    FOLDER_TO_UPLOAD: 'SSL_CERT/DEV2'

deploy_QAT1:
  extends:
    - .deploy_sslcert_template
  variables:
    SSH_USER: $SSH_USER
    SSH_PWD: $SSH_PWD
    DOWNLOAD_LOCATION: "$ARTIFACTORY_URL/$REPO_KEY_POC/ambassador/${CI_PIPELINE_ID}"
    REMOTE_LOCATION: '/deploy/bscs/Cert'
    CERT_NAME: 'pl-l2-bscs-01-traf.pl.lab.uprising.t-mobile.com.p12'
    CERT_PWD: $CERT_PWD
    ENV_HOST: $QAT1_IP_ADDRESS
    FOLDER_TO_UPLOAD: 'SSL_CERT/QAT1'
