stages:
  - deploy

deploy_cdpsdp1:
  extends:
    - .deploy_sslcert_template
  variables:
    SSH_USER: $SSH_USER
    SSH_PWD: $SSH_PWD
    DOWNLOAD_LOCATION: "$ARTIFACTORY_URL/$REPO_KEY_POC/ambassador/${CI_PIPELINE_ID}"
    REMOTE_LOCATION: '/deploy/bscs/Cert'
    CERT_NAME: 'pl-dev-cdp-sd1-bscs-traf.lab.uprising.t-mobile.com.p12'
    CERT_PWD: $CERT_PWD
    ENV_HOST: $CDPSD1_IP_ADDRESS
    FOLDER_TO_UPLOAD: 'SSL_CERT/CDPSD1'
